services:
  chat_api:
    build:
      dockerfile: Dockerfile
    container_name: chat_api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8080"
    depends_on:
      postgresql_chat_api:
        condition: service_healthy
    restart: on-failure

  postgresql_chat_api:
    image: postgres:latest
    container_name: postgresql_chat_api
    environment:
      POSTGRES_USER: IgnacioVillarreal
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: chatdb
    ports:
      - "5434:5432"
    volumes:
      - chatdb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "IgnacioVillarreal", "-d", "chatdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  chatdb_data: