services:
  chatdb:
    image: 'postgres:latest'
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: IgnacioVillarreal
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: chatdb
    volumes:
      - chatdb:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  chatapi:
    build:
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8082:8080
    depends_on:
      chatdb:
        condition: service_healthy
    restart: on-failure

volumes:
  chatdb: