spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    test:
      database:
        replace: any
cors:
  allowed-origins:
    - http://localhost:4200
jwt:
  secret: 23e586808ea364607079ec5b830ba702e80680339864b175eb2f5a13abd214e7
logging:
  level:
    org:
      springframework:
        security: DEBUG